[package]
name = "tb_client"
version = "0.1.0"
edition = "2024"

[features]
default = ["dev"] # TODO: REMOVE
dev = []

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.131"
reqwest = { version = "0.12.11", features = ["json", "multipart"] }
server_types = { path = "../server_types" }
url = "2"
thiserror = "2.0.0"
